In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_predict, cross_val_score, cross_validate
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, recall_score, precision_score, accuracy_score
from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings('ignore')

# <font color='#0000FF'>Table of Contents</font>

[1 : Exploring the data](#1)

[2 : Normalization of variables for modeling](#2)

<p style="padding:10px;background-color:#B9B7BD;margin:0;color:#000C66;font-family:sans serif;font-size:240%;text-align:center; overflow:hidden; font-weight:500; font-style:italic"><a id='1'></a>1. Exploring the data</p>

<p style="text-align:center; "></p>

Data exploration is a crucial step in the data analysis process. This phase allows for understanding the nature of the data, identifying trends, patterns, and laying the groundwork for more in-depth analyses. Here are some steps and techniques commonly used during data exploration:

- Understanding the Data: start by examining basic data features such as dataset size, variable types, and the initial rows to gain an initial overview.

- Descriptive Statistics: calculate descriptive statistics like mean, median, standard deviation, etc., to get an idea of the distribution of numerical variables.

- Visualization: Use graphs to visualize the data. Histograms, box plots, and scatter plots are useful for understanding the distribution, dispersion, and relationships between variables.

- Correlation Analysis: explore the relationships between variables by calculating correlations. This can reveal interesting associations or potential collinearities.

- Segmentation: if the data allows, perform segmentation to identify homogeneous subgroups. This can help tailor analyses based on specific characteristics.

- Preliminary Statistical Tests: if needed, conduct preliminary statistical tests to assess normality, equality of variances, etc.

In [2]:
df = pd.read_csv('heart_disease_2022_cleaned.csv')
df.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  object
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  object
 10  HadAngina                  246022 non-null  object
 11  HadStroke                  246022 non-null  object
 12  HadAsthma                  246022 non-null  object
 13  HadSkinCancer              246022 non-null  object
 14  HadCOPD                    246022 non-null  object
 15  HadDepressiveDisorder      246022 non-null  object
 16  HadKidneyDisease           246022 non-null  object
 17  HadArthritis               246022 non-null  object
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  object
 20  BlindOrVisionDifficulty    246022 non-null  object
 21  DifficultyConcentrating    246022 non-null  object
 22  DifficultyWalking          246022 non-null  object
 23  DifficultyDressingBathing  246022 non-null  object
 24  DifficultyErrands          246022 non-null  object
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  object
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  object
 34  HIVTesting                 246022 non-null  object
 35  FluVaxLast12               246022 non-null  object
 36  PneumoVaxEver              246022 non-null  object
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  object
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), object(34)
memory usage: 75.1+ MB

In [6]:
df.shape

(246022, 40)

In [5]:
df.describe()

,PhysicalHealthDays,MentalHealthDays,SleepHours,HeightInMeters,WeightInKilograms,BMI
count,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000
mean,4.119026,4.167140,7.021331,1.705150,83.615179,28.668136
std,8.405844,8.102687,1.440681,0.106654,21.323156,6.513973
min,0.000000,0.000000,1.000000,0.910000,28.120000,12.020000
25%,0.000000,0.000000,6.000000,1.630000,68.040000,24.270000
50%,0.000000,0.000000,7.000000,1.700000,81.650000,27.460000
75%,3.000000,4.000000,8.000000,1.780000,95.250000,31.890000
max,30.000000,30.000000,24.000000,2.410000,292.570000,97.650000

In [7]:
for column_content in df.columns:
    print(column_content)
    print(df[column_content].unique(),"\n")

State
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico'
 'Virgin Islands']

Sex
['Female' 'Male']

GeneralHealth
['Very good' 'Fair' 'Good' 'Excellent' 'Poor']

PhysicalHealthDays
[ 4.  0.  5.  3.  2. 25. 30. 15. 29.  8. 16. 20. 10.  9.  7.  1. 21.  6.
 27. 14. 12. 11. 13. 28. 17. 23. 24. 26. 18. 22. 19.]

MentalHealthDays
[ 0. 15.  4. 25.  5. 30. 27.  3.  2.  1. 10. 20. 21.  6.  7.  8. 14.  9.
 12. 18. 29. 28. 17. 11. 16. 13. 26. 22. 24. 19. 23.]

LastCheckupTime
['Within past year (anytime less than 12 months ago)'
 '5 or more years ago'
 'Within past 2 years (1 year but less than 2 years ago)'
 'Within past 5 years (2 years but less than 5 years ago)']

PhysicalActivities
['Yes' 'No']

SleepHours
[ 9.  6.  8.  5.  7. 10.  4. 12.  3. 18. 11.  2.  1. 16. 14. 15. 13. 20.
 24. 23. 19. 17. 22.]

RemovedTeeth
['None of them' '6 or more, but not all' '1 to 5' 'All']

HadHeartAttack
['No' 'Yes']

HadAngina
['No' 'Yes']

HadStroke
['No' 'Yes']

HadAsthma
['No' 'Yes']

HadSkinCancer
['No' 'Yes']

HadCOPD
['No' 'Yes']

HadDepressiveDisorder
['No' 'Yes']

HadKidneyDisease
['No' 'Yes']

HadArthritis
['Yes' 'No']

HadDiabetes
['No' 'Yes' 'Yes, but only during pregnancy (female)'
 'No, pre-diabetes or borderline diabetes']

DeafOrHardOfHearing
['No' 'Yes']

BlindOrVisionDifficulty
['No' 'Yes']

DifficultyConcentrating
['No' 'Yes']

DifficultyWalking
['No' 'Yes']

DifficultyDressingBathing
['No' 'Yes']

DifficultyErrands
['No' 'Yes']

SmokerStatus
['Former smoker' 'Never smoked' 'Current smoker - now smokes every day'
 'Current smoker - now smokes some days']

ECigaretteUsage
['Never used e-cigarettes in my entire life' 'Use them some days'
 'Not at all (right now)' 'Use them every day']

ChestScan
['No' 'Yes']

RaceEthnicityCategory
['White only, Non-Hispanic' 'Black only, Non-Hispanic'
 'Other race only, Non-Hispanic' 'Multiracial, Non-Hispanic' 'Hispanic']

AgeCategory
['Age 65 to 69' 'Age 70 to 74' 'Age 75 to 79' 'Age 80 or older'
 'Age 50 to 54' 'Age 40 to 44' 'Age 60 to 64' 'Age 55 to 59'
 'Age 45 to 49' 'Age 35 to 39' 'Age 25 to 29' 'Age 30 to 34'
 'Age 18 to 24']

HeightInMeters
[1.6  1.78 1.85 1.7  1.55 1.63 1.75 1.68 1.83 1.52 1.88 1.5  1.73 1.65
 1.8  1.57 1.91 1.47 1.42 1.22 1.93 2.01 1.96 1.98 1.45 1.35 1.76 2.03
 2.16 1.51 1.53 1.69 1.56 1.84 1.9  1.54 1.72 1.87 1.74 1.4  1.64 1.58
 1.62 1.79 1.67 1.46 1.89 1.61 1.3  1.37 2.13 2.06 2.11 0.91 2.26 2.18
 1.77 2.36 1.59 1.86 1.82 1.66 1.71 1.95 1.05 2.08 1.49 1.38 1.81 1.44
 1.48 1.19 1.32 1.24 1.07 1.04 1.27 1.1  1.92 1.2  2.24 1.12 1.03 0.97
 1.25 2.29 1.16 1.18 1.09 2.41 1.   1.17 1.08 1.43 1.14 1.02 2.   2.02
 0.95 2.34 2.21]

WeightInKilograms
[ 71.67  95.25 108.86  90.72  79.38 120.2   88.    74.84  78.02  63.5
 122.47 115.67  81.65  86.18  76.2   54.88  72.57  88.45 104.33  52.16
  68.04  65.77  56.7   94.8  123.83  50.8   68.95 113.4   83.91  77.56
  68.49  82.1   80.74 106.14  58.06  61.69  57.61  84.82  70.76  70.31
  91.63 102.06  48.08  61.23 109.77  99.79  58.97 110.68  64.86 111.13
  45.36  79.83  98.88  55.34 101.6   77.11  93.89  71.21  49.9   96.16
 163.29 120.66  97.52  88.9   44.91  85.73  83.46  92.99 132.    67.59
  92.08  73.48 107.5  107.95  91.17  74.39  64.41  62.6   46.72 103.42
  87.09  89.81  83.01 100.7   56.25  96.62  66.68  67.13  69.4   58.51
  78.93  95.71  63.05  49.44 127.01 145.15 122.02 107.05 126.55 117.03
  47.17 181.44  65.32 117.93 136.08  78.47  52.62 121.56  73.94  82.55
 106.59  59.87 110.22  62.14  51.71  93.44  54.43  85.28  59.42  66.22
  76.66  55.79  75.3   97.07  87.54  69.85 124.74  63.96  47.63  94.35
  97.98  89.36  92.53 101.15 149.69 129.27  84.37 195.04  99.34 114.31
  53.07  81.19  75.75 124.28 112.94  80.29 114.76  45.81  53.52 133.81
  51.26 158.76  60.78  46.27  72.12 131.54 127.91  53.98  98.43 130.63
 143.34 102.51 115.21  90.26 166.92 109.32  40.37 135.62 204.12 129.73
 127.46 138.35 105.69 119.75  48.53 140.61 105.23 139.25 126.1  135.17
 102.97 122.92  57.15  38.56  60.33 131.09 148.78 116.57 112.49  86.64
 112.04 172.37 133.36 118.84  50.35 103.87 111.58 121.11 113.85  73.03
 142.88 134.26 123.38  37.19 119.29  36.29  48.99  43.09  41.73  35.38
 104.78 144.24 167.83 149.23  37.65  86.   147.42 165.56 154.22 136.98
 108.41 155.58 206.38 148.32  42.18  44.45  90.   191.87 249.48  67.
  44.    40.82 156.49  53.   139.71 130.18 118.39 100.   151.95 165.11
  43.54 134.72 141.52 125.19  75.   250.   116.12  73.   100.24  74.
 200.    80.    82.    54.    66.   152.41  39.46  41.28 190.51 188.24
  59.    70.   170.1   46.   265.   168.74 190.    55.    93.   159.66
  78.    38.1  185.07 104.   183.7  125.65  68.   134.   130.    32.21
 143.79 137.89 179.17 105.    65.    32.   292.57  85.    72.   174.63
  50.   128.37  62.    87.   176.9   39.92  76.   128.82  58.   156.04
 121.    42.64  89.   146.96 146.06 171.46 227.25  29.48 190.06 161.03
 226.8  132.45 137.44  64.    56.   141.07  52.    63.   120.    83.
  57.    31.75  77.    96.    60.   115.    41.   150.59 272.16  48.
  39.01  95.   197.31 158.3   45.    94.   240.4   49.   157.85 108.
 185.    61.    34.02 132.9   84.   229.97 138.8   81.    79.    92.
 107.   155.13 208.65  69.   111.   110.   151.05 210.   140.16  35.83
 146.51 117.48 102.   125.   151.5   36.74  38.   135.    71.   147.87
 153.77 170.    91.    98.   192.32 186.88 118.   160.12 160.   170.55
 201.85 184.16 175.09 142.43 169.   166.01 180.53 196.41 162.39  40.
 171.91 195.95 136.53 153.31 159.21 164.2  219.99 141.97 173.27  34.47
 213.19 276.24 199.58 215.46 217.72 175.99 200.03 230.88  33.57 185.52
 103.   152.86 101.   160.57 150.14 157.4  145.   150.   163.75 191.42
 174.18 164.65 256.28 205.48 192.78 161.48 178.26 179.62 144.7  205.02
 178.72 154.68 166.47 177.81 200.49 231.79 238.14 227.7  273.52 211.83
 223.62 197.77 189.15 185.97 250.38 183.25 181.89 222.26 231.33 180.08
 202.76 180.   164.   156.94 114.   122.   161.93 137.   162.84 188.69
 234.51 199.13 203.21 145.6  173.73 263.08 154.   239.04 177.35 224.98
 117.    37.    97.   210.92 273.06 203.66 238.59 113.   224.53 169.64
 146.   201.4  220.    34.93 254.01 212.73 176.45 184.61 124.   152.
 233.6  193.23 205.   244.94 229.06  47.   167.38  99.    28.12 235.87
 171.   212.28 180.98 169.19 175.54  30.84 116.   168.28 123.   186.43
 172.82 182.8  217.27 182.34 246.3   30.39]

BMI
[27.99 30.13 31.66 ... 38.8  58.95 45.28]

AlcoholDrinkers
['No' 'Yes']

HIVTesting
['No' 'Yes']

FluVaxLast12
['Yes' 'No']

PneumoVaxEver
['Yes' 'No']

TetanusLast10Tdap
['Yes, received Tdap' 'Yes, received tetanus shot but not sure what type'
 'No, did not receive any tetanus shot in the past 10 years'
 'Yes, received tetanus shot, but not Tdap']

HighRiskLastYear
['No' 'Yes']

CovidPos
['No' 'Yes'
 'Tested positive using home test without a health professional']

We have 40 variables, both categorical and quantitative. Several of them are objects that contain different types of information. We have closed Yes or No responses, evaluation responses, quantity responses, etc. Regarding the Float variables, it is very heterogeneous, which is understandable given the nature of each variable. 

- Therefore, it is necessary to standardize and normalize all these data for predictive modeling


#### I will not present visualizations in this notebook as I have already done so in another notebook for the same dataframe LINK. Here, I will primarily focus on machine learning modeling. If you're interested, you can refer to my previous notebook to see how the data is distributed through various visualizations.


<p style="padding:10px;background-color:#B9B7BD;margin:0;color:#000C66;font-family:sans serif;font-size:240%;text-align:center; overflow:hidden; font-weight:500; font-style:italic"><a id='2'></a>2. Normalization of variables for modeling</p>

<p style="text-align:center; "></p>

There will be a first step to transform categorical variables into numerical. I will use Replace() and lambda(). 

Then, there will be normalization of numerical variables with MinMaxScaler(), which will be done once the data has been split (X_train and X_test) to avoid overfitting.

In [8]:
dict_replace = {'No':0, 'Yes' : 1} 
df = df.replace(dict_replace)

dict_GeneralHealth = {'Excellent': 0, 'Very good' : 1, 'Good' : 2, 'Fair': 3, 'Poor': 4}
df['GeneralHealth'] = df['GeneralHealth'].replace(dict_GeneralHealth)

dict_RemovedTeeth = {'None of them': 0, '1 to 5' : 1, '6 or more, but not all' : 2, 'All': 3}
df['RemovedTeeth'] = df['RemovedTeeth'].replace(dict_RemovedTeeth)

dict_HadDiabetes = {'No': 0, 'Yes' : 1, 'Yes, but only during pregnancy (female)' : 2, 
                    'No, pre-diabetes or borderline diabetes': 3}
df['HadDiabetes'] = df['HadDiabetes'].replace(dict_HadDiabetes)

dict_SmokerStatus = {'Never smoked': 0, 'Current smoker - now smokes some days' : 1, 
                     'Current smoker - now smokes every day' : 2, 'Former smoker': 3}
df['SmokerStatus'] = df['SmokerStatus'].replace(dict_SmokerStatus)

dict_ECigaretteUsage = {'Never used e-cigarettes in my entire life': 0, 
                        'Use them every day' : 1, 'Use them some days' : 2, 'Not at all (right now)': 3}
df['ECigaretteUsage'] = df['ECigaretteUsage'].replace(dict_ECigaretteUsage)

dict_TetanusLast10Tdap = {'Yes, received Tdap': 0,'Yes, received tetanus shot but not sure what type' : 1, 
                          'Yes, received tetanus shot, but not Tdap' : 2, 
                          'No, did not receive any tetanus shot in the past 10 years': 3}
df['TetanusLast10Tdap'] = df['TetanusLast10Tdap'].replace(dict_TetanusLast10Tdap)

dict_CovidPos = {'No': 0, 'Yes' : 1, 'Tested positive using home test without a health professional' : 2}
df['CovidPos'] = df['CovidPos'].replace(dict_CovidPos)

In [9]:
df['BMI'] = df['BMI'].apply(lambda x : 0 if x <= 24.9 else 1)
df['BMI'].value_counts()

1    173462
0     72560
Name: BMI, dtype: int64

In [10]:
df['Sex'] = df['Sex'].apply(lambda x : 0 if x == 'Female' else 1)
df['Sex'].value_counts()

0    127811
1    118211
Name: Sex, dtype: int64

In [11]:
df['RaceEthnicityCategory'] = df['RaceEthnicityCategory'].apply(lambda x : 0 if x =='White only, Non-Hispanic'else 1)
df['RaceEthnicityCategory'].value_counts()

0    186336
1     59686
Name: RaceEthnicityCategory, dtype: int64

In [12]:
df['AgeCategory'] = df['AgeCategory'].replace(to_replace = df['AgeCategory'].unique(), value =  np.arange(0,13,1))

In [13]:
for column_content in df.columns:
    print(column_content)
    print(df[column_content].unique(),"\n")

State
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'District of Columbia' 'Florida' 'Georgia'
 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas' 'Kentucky'
 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan' 'Minnesota'
 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada' 'New Hampshire'
 'New Jersey' 'New Mexico' 'New York' 'North Carolina' 'North Dakota'
 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Rhode Island' 'South Carolina'
 'South Dakota' 'Tennessee' 'Texas' 'Utah' 'Vermont' 'Virginia'
 'Washington' 'West Virginia' 'Wisconsin' 'Wyoming' 'Guam' 'Puerto Rico'
 'Virgin Islands']

Sex
[0 1]

GeneralHealth
[1 3 2 0 4]

PhysicalHealthDays
[ 4.  0.  5.  3.  2. 25. 30. 15. 29.  8. 16. 20. 10.  9.  7.  1. 21.  6.
 27. 14. 12. 11. 13. 28. 17. 23. 24. 26. 18. 22. 19.]

MentalHealthDays
[ 0. 15.  4. 25.  5. 30. 27.  3.  2.  1. 10. 20. 21.  6.  7.  8. 14.  9.
 12. 18. 29. 28. 17. 11. 16. 13. 26. 22. 24. 19. 23.]

LastCheckupTime
['Within past year (anytime less than 12 months ago)'
 '5 or more years ago'
 'Within past 2 years (1 year but less than 2 years ago)'
 'Within past 5 years (2 years but less than 5 years ago)']

PhysicalActivities
[1 0]

SleepHours
[ 9.  6.  8.  5.  7. 10.  4. 12.  3. 18. 11.  2.  1. 16. 14. 15. 13. 20.
 24. 23. 19. 17. 22.]

RemovedTeeth
[0 2 1 3]

HadHeartAttack
[0 1]

HadAngina
[0 1]

HadStroke
[0 1]

HadAsthma
[0 1]

HadSkinCancer
[0 1]

HadCOPD
[0 1]

HadDepressiveDisorder
[0 1]

HadKidneyDisease
[0 1]

HadArthritis
[1 0]

HadDiabetes
[0 1 2 3]

DeafOrHardOfHearing
[0 1]

BlindOrVisionDifficulty
[0 1]

DifficultyConcentrating
[0 1]

DifficultyWalking
[0 1]

DifficultyDressingBathing
[0 1]

DifficultyErrands
[0 1]

SmokerStatus
[3 0 2 1]

ECigaretteUsage
[0 2 3 1]

ChestScan
[0 1]

RaceEthnicityCategory
[0 1]

AgeCategory
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]

HeightInMeters
[1.6  1.78 1.85 1.7  1.55 1.63 1.75 1.68 1.83 1.52 1.88 1.5  1.73 1.65
 1.8  1.57 1.91 1.47 1.42 1.22 1.93 2.01 1.96 1.98 1.45 1.35 1.76 2.03
 2.16 1.51 1.53 1.69 1.56 1.84 1.9  1.54 1.72 1.87 1.74 1.4  1.64 1.58
 1.62 1.79 1.67 1.46 1.89 1.61 1.3  1.37 2.13 2.06 2.11 0.91 2.26 2.18
 1.77 2.36 1.59 1.86 1.82 1.66 1.71 1.95 1.05 2.08 1.49 1.38 1.81 1.44
 1.48 1.19 1.32 1.24 1.07 1.04 1.27 1.1  1.92 1.2  2.24 1.12 1.03 0.97
 1.25 2.29 1.16 1.18 1.09 2.41 1.   1.17 1.08 1.43 1.14 1.02 2.   2.02
 0.95 2.34 2.21]

WeightInKilograms
[ 71.67  95.25 108.86  90.72  79.38 120.2   88.    74.84  78.02  63.5
 122.47 115.67  81.65  86.18  76.2   54.88  72.57  88.45 104.33  52.16
  68.04  65.77  56.7   94.8  123.83  50.8   68.95 113.4   83.91  77.56
  68.49  82.1   80.74 106.14  58.06  61.69  57.61  84.82  70.76  70.31
  91.63 102.06  48.08  61.23 109.77  99.79  58.97 110.68  64.86 111.13
  45.36  79.83  98.88  55.34 101.6   77.11  93.89  71.21  49.9   96.16
 163.29 120.66  97.52  88.9   44.91  85.73  83.46  92.99 132.    67.59
  92.08  73.48 107.5  107.95  91.17  74.39  64.41  62.6   46.72 103.42
  87.09  89.81  83.01 100.7   56.25  96.62  66.68  67.13  69.4   58.51
  78.93  95.71  63.05  49.44 127.01 145.15 122.02 107.05 126.55 117.03
  47.17 181.44  65.32 117.93 136.08  78.47  52.62 121.56  73.94  82.55
 106.59  59.87 110.22  62.14  51.71  93.44  54.43  85.28  59.42  66.22
  76.66  55.79  75.3   97.07  87.54  69.85 124.74  63.96  47.63  94.35
  97.98  89.36  92.53 101.15 149.69 129.27  84.37 195.04  99.34 114.31
  53.07  81.19  75.75 124.28 112.94  80.29 114.76  45.81  53.52 133.81
  51.26 158.76  60.78  46.27  72.12 131.54 127.91  53.98  98.43 130.63
 143.34 102.51 115.21  90.26 166.92 109.32  40.37 135.62 204.12 129.73
 127.46 138.35 105.69 119.75  48.53 140.61 105.23 139.25 126.1  135.17
 102.97 122.92  57.15  38.56  60.33 131.09 148.78 116.57 112.49  86.64
 112.04 172.37 133.36 118.84  50.35 103.87 111.58 121.11 113.85  73.03
 142.88 134.26 123.38  37.19 119.29  36.29  48.99  43.09  41.73  35.38
 104.78 144.24 167.83 149.23  37.65  86.   147.42 165.56 154.22 136.98
 108.41 155.58 206.38 148.32  42.18  44.45  90.   191.87 249.48  67.
  44.    40.82 156.49  53.   139.71 130.18 118.39 100.   151.95 165.11
  43.54 134.72 141.52 125.19  75.   250.   116.12  73.   100.24  74.
 200.    80.    82.    54.    66.   152.41  39.46  41.28 190.51 188.24
  59.    70.   170.1   46.   265.   168.74 190.    55.    93.   159.66
  78.    38.1  185.07 104.   183.7  125.65  68.   134.   130.    32.21
 143.79 137.89 179.17 105.    65.    32.   292.57  85.    72.   174.63
  50.   128.37  62.    87.   176.9   39.92  76.   128.82  58.   156.04
 121.    42.64  89.   146.96 146.06 171.46 227.25  29.48 190.06 161.03
 226.8  132.45 137.44  64.    56.   141.07  52.    63.   120.    83.
  57.    31.75  77.    96.    60.   115.    41.   150.59 272.16  48.
  39.01  95.   197.31 158.3   45.    94.   240.4   49.   157.85 108.
 185.    61.    34.02 132.9   84.   229.97 138.8   81.    79.    92.
 107.   155.13 208.65  69.   111.   110.   151.05 210.   140.16  35.83
 146.51 117.48 102.   125.   151.5   36.74  38.   135.    71.   147.87
 153.77 170.    91.    98.   192.32 186.88 118.   160.12 160.   170.55
 201.85 184.16 175.09 142.43 169.   166.01 180.53 196.41 162.39  40.
 171.91 195.95 136.53 153.31 159.21 164.2  219.99 141.97 173.27  34.47
 213.19 276.24 199.58 215.46 217.72 175.99 200.03 230.88  33.57 185.52
 103.   152.86 101.   160.57 150.14 157.4  145.   150.   163.75 191.42
 174.18 164.65 256.28 205.48 192.78 161.48 178.26 179.62 144.7  205.02
 178.72 154.68 166.47 177.81 200.49 231.79 238.14 227.7  273.52 211.83
 223.62 197.77 189.15 185.97 250.38 183.25 181.89 222.26 231.33 180.08
 202.76 180.   164.   156.94 114.   122.   161.93 137.   162.84 188.69
 234.51 199.13 203.21 145.6  173.73 263.08 154.   239.04 177.35 224.98
 117.    37.    97.   210.92 273.06 203.66 238.59 113.   224.53 169.64
 146.   201.4  220.    34.93 254.01 212.73 176.45 184.61 124.   152.
 233.6  193.23 205.   244.94 229.06  47.   167.38  99.    28.12 235.87
 171.   212.28 180.98 169.19 175.54  30.84 116.   168.28 123.   186.43
 172.82 182.8  217.27 182.34 246.3   30.39]

BMI
[1 0]

AlcoholDrinkers
[0 1]

HIVTesting
[0 1]

FluVaxLast12
[1 0]

PneumoVaxEver
[1 0]

TetanusLast10Tdap
[0 1 3 2]

HighRiskLastYear
[0 1]

CovidPos
[0 1 2]